name: Update Formula

on:
  release:
    types: [published]

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Get latest release information
        id: get_release
        run: |
          python << END
          import requests
          import yaml

          response = requests.get('https://api.github.com/repos/michielnijenhuis/env-check/releases/latest')
          release_data = response.json()

          latest_url = release_data['tarball_url']

          with open('release_data.yaml', 'w') as f:
              yaml.dump({'url': latest_url}, f)
          END

      - name: Download release archive
        run: |
          LATEST_DATA=$(cat release_data.yaml)
          wget $(echo "$LATEST_DATA['url']") -O latest.tar.gz

      - name: Calculate SHA256 checksum
        run: |
          CHECKSUM=$(shasum -a 256 latest.tar.gz | cut -d " " -f 1)
          echo "::set-output name=checksum::$CHECKSUM"

      - name: Update Formula file
        run: |
          LATEST_DATA=$(cat release_data.yaml)
          sed -i "s#url \".*\"#url \"$LATEST_DATA['url']\"#" ./Formula/envc.rb
          sed -i "s#sha256 \".*\"#sha256 \"$CHECKSUM\"#" ./Formula/envc.rb

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "release: auto-update formula file"
          git push
