name: Update Formula

on:
    release:
        types: [created]

jobs:
    update_formula:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Download release asset
              run: |
                  wget -O envc.tar.gz ${{ github.event.release.tarball_url }}

            - name: Calculate SHA256
              run: |
                  sha256=$(shasum -a 256 envc.tar.gz | cut -d' ' -f1)
                  echo "SHA256: $sha256" >> sha256.txt

            - name: Update Formula
              run: |
                  sed -i '' "s/url \"url\"/url \"${{ github.event.release.tarball_url }}\"/" ./Formula/envc.rb
                  sed -i '' "s/sha256 \"sha256\"/sha256 \"$(cat sha256.txt | tr -d '\n')\"/" ./Formula/envc.rb
